"""Add outreach growth engine.

Revision ID: 20260723_0006
Revises: 20260723_0005
Create Date: 2026-07-23 13:52:57.442391

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "20260723_0006"
down_revision: str | None = "20260723_0005"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "outreach_audiences",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("filter_definition", sa.JSON(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_outreach_audiences_created_by_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
            name=op.f("fk_outreach_audiences_owner_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_outreach_audiences")),
        sa.UniqueConstraint(
            "owner_id", "name", name=op.f("uq_outreach_audiences_owner_id")
        ),
    )
    op.create_table(
        "outreach_automations",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column(
            "trigger",
            sa.Enum(
                "lead_created",
                "lead_qualified",
                "deal_stage_changed",
                "email_replied",
                "email_bounced",
                "campaign_completed",
                name="outreach_automation_trigger",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "action",
            sa.Enum(
                "enroll_sequence",
                "send_notification",
                name="outreach_automation_action",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("conditions", sa.JSON(), nullable=False),
        sa.Column("action_config", sa.JSON(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_outreach_automations_created_by_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
            name=op.f("fk_outreach_automations_owner_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_outreach_automations")),
        sa.UniqueConstraint(
            "owner_id", "name", name=op.f("uq_outreach_automations_owner_id")
        ),
    )
    op.create_index(
        "ix_outreach_automations_trigger_active",
        "outreach_automations",
        ["trigger", "is_active"],
        unique=False,
    )
    op.create_table(
        "outreach_mailboxes",
        sa.Column(
            "provider",
            sa.Enum(
                "gmail",
                "microsoft_365",
                "smtp",
                name="mailbox_provider",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("email_address", sa.String(length=320), nullable=False),
        sa.Column("display_name", sa.String(length=200), nullable=True),
        sa.Column("credential_reference", sa.String(length=500), nullable=False),
        sa.Column("signature_html", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("daily_send_limit", sa.Integer(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "daily_send_limit > 0 AND daily_send_limit <= 10000",
            name=op.f("ck_outreach_mailboxes_daily_limit_range"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_outreach_mailboxes_created_by_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
            name=op.f("fk_outreach_mailboxes_owner_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_outreach_mailboxes")),
        sa.UniqueConstraint(
            "owner_id", "email_address", name=op.f("uq_outreach_mailboxes_owner_id")
        ),
    )
    op.create_index(
        "ix_outreach_mailboxes_owner_active",
        "outreach_mailboxes",
        ["owner_id", "is_active"],
        unique=False,
    )
    op.create_table(
        "outreach_sequences",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.String(length=1000), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "active",
                "paused",
                "completed",
                "archived",
                name="outreach_sequence_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_outreach_sequences_created_by_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
            name=op.f("fk_outreach_sequences_owner_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_outreach_sequences")),
        sa.UniqueConstraint(
            "owner_id", "name", name=op.f("uq_outreach_sequences_owner_id")
        ),
    )
    op.create_index(
        "ix_outreach_sequences_owner_status",
        "outreach_sequences",
        ["owner_id", "status"],
        unique=False,
    )
    op.create_table(
        "outreach_templates",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.String(length=1000), nullable=True),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("is_archived", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_outreach_templates_created_by_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
            name=op.f("fk_outreach_templates_owner_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_outreach_templates")),
        sa.UniqueConstraint(
            "owner_id", "name", name=op.f("uq_outreach_templates_owner_id")
        ),
    )
    op.create_index(
        "ix_outreach_templates_owner_archived",
        "outreach_templates",
        ["owner_id", "is_archived"],
        unique=False,
    )
    op.create_table(
        "outreach_campaigns",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("sequence_id", sa.Uuid(), nullable=False),
        sa.Column("audience_id", sa.Uuid(), nullable=False),
        sa.Column("mailbox_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "active",
                "paused",
                "completed",
                "archived",
                name="outreach_campaign_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["audience_id"],
            ["outreach_audiences.id"],
            name=op.f("fk_outreach_campaigns_audience_id_outreach_audiences"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_outreach_campaigns_created_by_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["mailbox_id"],
            ["outreach_mailboxes.id"],
            name=op.f("fk_outreach_campaigns_mailbox_id_outreach_mailboxes"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
            name=op.f("fk_outreach_campaigns_owner_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["sequence_id"],
            ["outreach_sequences.id"],
            name=op.f("fk_outreach_campaigns_sequence_id_outreach_sequences"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_outreach_campaigns")),
        sa.UniqueConstraint(
            "owner_id", "name", name=op.f("uq_outreach_campaigns_owner_id")
        ),
    )
    op.create_index(
        "ix_outreach_campaigns_owner_status",
        "outreach_campaigns",
        ["owner_id", "status"],
        unique=False,
    )
    op.create_index(
        "ix_outreach_campaigns_scheduled_at",
        "outreach_campaigns",
        ["scheduled_at"],
        unique=False,
    )
    op.create_table(
        "outreach_template_versions",
        sa.Column("template_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("subject", sa.String(length=500), nullable=False),
        sa.Column("body_html", sa.Text(), nullable=False),
        sa.Column("body_text", sa.Text(), nullable=True),
        sa.Column("variables", sa.JSON(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "version > 0", name=op.f("ck_outreach_template_versions_version_positive")
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_outreach_template_versions_created_by_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["template_id"],
            ["outreach_templates.id"],
            name=op.f("fk_outreach_template_versions_template_id_outreach_templates"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_outreach_template_versions")),
        sa.UniqueConstraint(
            "template_id",
            "version",
            name=op.f("uq_outreach_template_versions_template_id"),
        ),
    )
    op.create_table(
        "outreach_drafts",
        sa.Column("mailbox_id", sa.Uuid(), nullable=False),
        sa.Column("template_version_id", sa.Uuid(), nullable=True),
        sa.Column("contact_id", sa.Uuid(), nullable=True),
        sa.Column("to_email", sa.String(length=320), nullable=False),
        sa.Column("cc", sa.JSON(), nullable=False),
        sa.Column("bcc", sa.JSON(), nullable=False),
        sa.Column("subject", sa.String(length=500), nullable=False),
        sa.Column("body_html", sa.Text(), nullable=False),
        sa.Column("body_text", sa.Text(), nullable=True),
        sa.Column("variable_values", sa.JSON(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "pending_approval",
                "approved",
                "scheduled",
                "queued",
                "sent",
                "cancelled",
                name="outreach_draft_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["contact_id"],
            ["crm_contacts.id"],
            name=op.f("fk_outreach_drafts_contact_id_crm_contacts"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_outreach_drafts_created_by_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["mailbox_id"],
            ["outreach_mailboxes.id"],
            name=op.f("fk_outreach_drafts_mailbox_id_outreach_mailboxes"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
            name=op.f("fk_outreach_drafts_owner_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["template_version_id"],
            ["outreach_template_versions.id"],
            name=op.f(
                "fk_outreach_drafts_template_version_id_outreach_template_versions"
            ),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_outreach_drafts")),
    )
    op.create_index(
        "ix_outreach_drafts_owner_status",
        "outreach_drafts",
        ["owner_id", "status"],
        unique=False,
    )
    op.create_index(
        "ix_outreach_drafts_scheduled_at",
        "outreach_drafts",
        ["scheduled_at"],
        unique=False,
    )
    op.create_table(
        "outreach_enrollments",
        sa.Column("sequence_id", sa.Uuid(), nullable=False),
        sa.Column("campaign_id", sa.Uuid(), nullable=True),
        sa.Column("contact_id", sa.Uuid(), nullable=False),
        sa.Column("current_step", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "active",
                "paused",
                "completed",
                "archived",
                name="outreach_enrollment_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("next_execution_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["outreach_campaigns.id"],
            name=op.f("fk_outreach_enrollments_campaign_id_outreach_campaigns"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["contact_id"],
            ["crm_contacts.id"],
            name=op.f("fk_outreach_enrollments_contact_id_crm_contacts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
            name=op.f("fk_outreach_enrollments_owner_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["sequence_id"],
            ["outreach_sequences.id"],
            name=op.f("fk_outreach_enrollments_sequence_id_outreach_sequences"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_outreach_enrollments")),
        sa.UniqueConstraint(
            "sequence_id",
            "contact_id",
            name=op.f("uq_outreach_enrollments_sequence_id"),
        ),
    )
    op.create_index(
        "ix_outreach_enrollments_status_next",
        "outreach_enrollments",
        ["status", "next_execution_at"],
        unique=False,
    )
    op.create_table(
        "outreach_sequence_steps",
        sa.Column("sequence_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("delay_minutes", sa.Integer(), nullable=False),
        sa.Column("template_version_id", sa.Uuid(), nullable=False),
        sa.Column("requires_approval", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "delay_minutes >= 0",
            name=op.f("ck_outreach_sequence_steps_delay_nonnegative"),
        ),
        sa.CheckConstraint(
            "position >= 0",
            name=op.f("ck_outreach_sequence_steps_position_nonnegative"),
        ),
        sa.ForeignKeyConstraint(
            ["sequence_id"],
            ["outreach_sequences.id"],
            name=op.f("fk_outreach_sequence_steps_sequence_id_outreach_sequences"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["template_version_id"],
            ["outreach_template_versions.id"],
            name=op.f(
                "fk_outreach_sequence_steps_template_version_id_outreach_template_versions"
            ),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_outreach_sequence_steps")),
        sa.UniqueConstraint(
            "sequence_id",
            "position",
            name=op.f("uq_outreach_sequence_steps_sequence_id"),
        ),
    )
    op.create_table(
        "outreach_approvals",
        sa.Column("draft_id", sa.Uuid(), nullable=False),
        sa.Column("requested_by", sa.Uuid(), nullable=False),
        sa.Column("reviewer_id", sa.Uuid(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "approved",
                "rejected",
                "cancelled",
                name="outreach_approval_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("decision_reason", sa.String(length=1000), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["draft_id"],
            ["outreach_drafts.id"],
            name=op.f("fk_outreach_approvals_draft_id_outreach_drafts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["requested_by"],
            ["users.id"],
            name=op.f("fk_outreach_approvals_requested_by_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["reviewer_id"],
            ["users.id"],
            name=op.f("fk_outreach_approvals_reviewer_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_outreach_approvals")),
        sa.UniqueConstraint("draft_id", name=op.f("uq_outreach_approvals_draft_id")),
    )
    op.create_index(
        "ix_outreach_approvals_reviewer_status",
        "outreach_approvals",
        ["reviewer_id", "status"],
        unique=False,
    )
    op.create_table(
        "outreach_attachments",
        sa.Column("draft_id", sa.Uuid(), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("content_type", sa.String(length=200), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("storage_key", sa.String(length=1000), nullable=False),
        sa.Column("checksum_sha256", sa.String(length=64), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "size_bytes >= 0 AND size_bytes <= 26214400",
            name=op.f("ck_outreach_attachments_attachment_size_range"),
        ),
        sa.ForeignKeyConstraint(
            ["draft_id"],
            ["outreach_drafts.id"],
            name=op.f("fk_outreach_attachments_draft_id_outreach_drafts"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_outreach_attachments")),
    )
    op.create_table(
        "outreach_send_queue",
        sa.Column("draft_id", sa.Uuid(), nullable=False),
        sa.Column("enrollment_id", sa.Uuid(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "processing",
                "sent",
                "retry",
                "failed",
                "cancelled",
                name="outreach_queue_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("available_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("locked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("provider_message_id", sa.String(length=500), nullable=True),
        sa.Column("last_error_code", sa.String(length=100), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "attempt_count >= 0 AND max_attempts > 0",
            name=op.f("ck_outreach_send_queue_attempts_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["draft_id"],
            ["outreach_drafts.id"],
            name=op.f("fk_outreach_send_queue_draft_id_outreach_drafts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["enrollment_id"],
            ["outreach_enrollments.id"],
            name=op.f("fk_outreach_send_queue_enrollment_id_outreach_enrollments"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_outreach_send_queue")),
        sa.UniqueConstraint("draft_id", name=op.f("uq_outreach_send_queue_draft_id")),
    )
    op.create_index(
        "ix_outreach_queue_status_available",
        "outreach_send_queue",
        ["status", "available_at"],
        unique=False,
    )
    op.create_table(
        "outreach_delivery_events",
        sa.Column("queue_item_id", sa.Uuid(), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "sent",
                "delivered",
                "opened",
                "clicked",
                "replied",
                "bounced",
                "unsubscribed",
                name="outreach_delivery_event_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("provider_event_id", sa.String(length=500), nullable=False),
        sa.Column("safe_metadata", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["queue_item_id"],
            ["outreach_send_queue.id"],
            name=op.f("fk_outreach_delivery_events_queue_item_id_outreach_send_queue"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_outreach_delivery_events")),
        sa.UniqueConstraint(
            "provider_event_id",
            name=op.f("uq_outreach_delivery_events_provider_event_id"),
        ),
    )
    op.create_index(
        "ix_outreach_events_occurred_at",
        "outreach_delivery_events",
        ["occurred_at"],
        unique=False,
    )
    op.create_index(
        "ix_outreach_events_queue_type",
        "outreach_delivery_events",
        ["queue_item_id", "type"],
        unique=False,
    )
    op.create_table(
        "outreach_executions",
        sa.Column("enrollment_id", sa.Uuid(), nullable=False),
        sa.Column("step_id", sa.Uuid(), nullable=False),
        sa.Column("queue_item_id", sa.Uuid(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "processing",
                "sent",
                "retry",
                "failed",
                "cancelled",
                name="outreach_execution_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("executed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["enrollment_id"],
            ["outreach_enrollments.id"],
            name=op.f("fk_outreach_executions_enrollment_id_outreach_enrollments"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["queue_item_id"],
            ["outreach_send_queue.id"],
            name=op.f("fk_outreach_executions_queue_item_id_outreach_send_queue"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["step_id"],
            ["outreach_sequence_steps.id"],
            name=op.f("fk_outreach_executions_step_id_outreach_sequence_steps"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_outreach_executions")),
        sa.UniqueConstraint(
            "enrollment_id",
            "step_id",
            name=op.f("uq_outreach_executions_enrollment_id"),
        ),
    )
    with op.batch_alter_table("notifications") as batch:
        batch.drop_constraint("notification_type", type_="check")
        batch.alter_column(
            "type",
            existing_type=sa.String(length=22),
            type_=sa.String(length=27),
            existing_nullable=False,
        )
        batch.create_check_constraint(
            "notification_type",
            "type IN ('task_assigned', 'task_due_soon', 'task_overdue', "
            "'project_status_changed', 'system', 'lead_assigned', "
            "'deal_assigned', 'deal_stage_changed', 'lead_qualified', "
            "'lead_converted', 'follow_up_due', 'crm_activity_assigned', "
            "'outreach_approval_requested', 'outreach_approval_decided', "
            "'outreach_send_failed', 'campaign_completed')",
        )
    with op.batch_alter_table("audit_logs") as batch:
        batch.drop_constraint("audit_entity", type_="check")
        batch.create_check_constraint(
            "audit_entity",
            "entity IN ('project', 'task', 'company', 'contact', 'lead', "
            "'pipeline', 'pipeline_stage', 'deal', 'crm_note', "
            "'crm_activity', 'mailbox', 'email_template', 'email_draft', "
            "'sequence', 'campaign', 'automation')",
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("audit_logs") as batch:
        batch.drop_constraint("audit_entity", type_="check")
        batch.create_check_constraint(
            "audit_entity",
            "entity IN ('project', 'task', 'company', 'contact', 'lead', "
            "'pipeline', 'pipeline_stage', 'deal', 'crm_note', "
            "'crm_activity')",
        )
    with op.batch_alter_table("notifications") as batch:
        batch.drop_constraint("notification_type", type_="check")
        batch.alter_column(
            "type",
            existing_type=sa.String(length=27),
            type_=sa.String(length=22),
            existing_nullable=False,
        )
        batch.create_check_constraint(
            "notification_type",
            "type IN ('task_assigned', 'task_due_soon', 'task_overdue', "
            "'project_status_changed', 'system', 'lead_assigned', "
            "'deal_assigned', 'deal_stage_changed', 'lead_qualified', "
            "'lead_converted', 'follow_up_due', "
            "'crm_activity_assigned')",
        )
    op.drop_table("outreach_executions")
    op.drop_index(
        "ix_outreach_events_queue_type", table_name="outreach_delivery_events"
    )
    op.drop_index(
        "ix_outreach_events_occurred_at", table_name="outreach_delivery_events"
    )
    op.drop_table("outreach_delivery_events")
    op.drop_index(
        "ix_outreach_queue_status_available", table_name="outreach_send_queue"
    )
    op.drop_table("outreach_send_queue")
    op.drop_table("outreach_attachments")
    op.drop_index(
        "ix_outreach_approvals_reviewer_status", table_name="outreach_approvals"
    )
    op.drop_table("outreach_approvals")
    op.drop_table("outreach_sequence_steps")
    op.drop_index(
        "ix_outreach_enrollments_status_next", table_name="outreach_enrollments"
    )
    op.drop_table("outreach_enrollments")
    op.drop_index("ix_outreach_drafts_scheduled_at", table_name="outreach_drafts")
    op.drop_index("ix_outreach_drafts_owner_status", table_name="outreach_drafts")
    op.drop_table("outreach_drafts")
    op.drop_table("outreach_template_versions")
    op.drop_index("ix_outreach_campaigns_scheduled_at", table_name="outreach_campaigns")
    op.drop_index("ix_outreach_campaigns_owner_status", table_name="outreach_campaigns")
    op.drop_table("outreach_campaigns")
    op.drop_index(
        "ix_outreach_templates_owner_archived", table_name="outreach_templates"
    )
    op.drop_table("outreach_templates")
    op.drop_index("ix_outreach_sequences_owner_status", table_name="outreach_sequences")
    op.drop_table("outreach_sequences")
    op.drop_index("ix_outreach_mailboxes_owner_active", table_name="outreach_mailboxes")
    op.drop_table("outreach_mailboxes")
    op.drop_index(
        "ix_outreach_automations_trigger_active", table_name="outreach_automations"
    )
    op.drop_table("outreach_automations")
    op.drop_table("outreach_audiences")
    # ### end Alembic commands ###
