"""Database models."""

from app.database.models.agent import (
    AgentApproval,
    AgentApprovalStatus,
    AgentAttachment,
    AgentAttachmentStatus,
    AgentContextSnapshot,
    AgentConversation,
    AgentDefinition,
    AgentMemory,
    AgentMemoryScope,
    AgentMemoryType,
    AgentMessage,
    AgentRiskLevel,
    AgentRun,
    AgentRunStatus,
    AgentStatus,
    AgentToolDefinition,
    AgentToolExecution,
    ConversationPriority,
    ConversationStatus,
    MessageContentType,
    MessageRole,
    ToolExecutionMode,
    ToolExecutionStatus,
)
from app.database.models.audit_log import AuditAction, AuditEntity, AuditLog
from app.database.models.base import (
    Base,
    TimestampMixin,
    UUIDPrimaryKeyMixin,
)
from app.database.models.background import (
    BackgroundJobAttempt,
    BackgroundJobDefinition,
    BackgroundJobEvent,
    BackgroundJobExecution,
    BackgroundJobSchedule,
)
from app.database.models.crm import (
    CRMActivity,
    CRMActivityType,
    CRMNote,
    Company,
    CompanyStatus,
    Contact,
    ContactStatus,
    Deal,
    DealStatus,
    Lead,
    LeadSource,
    LeadStatus,
    Pipeline,
    PipelineStage,
)
from app.database.models.enums import ProjectStatus, TaskPriority, TaskStatus
from app.database.models.notification import Notification, NotificationType
from app.database.models.outreach import (
    ApprovalStatus,
    AutomationAction,
    AutomationRule,
    AutomationTrigger,
    Campaign,
    DeliveryEvent,
    DeliveryEventType,
    DraftStatus,
    DynamicAudience,
    EmailAttachment,
    EmailDraft,
    EmailTemplate,
    EmailTemplateVersion,
    MailboxConnection,
    MailboxProvider,
    OutreachApproval,
    OutreachStatus,
    QueueStatus,
    SendQueueItem,
    Sequence,
    SequenceEnrollment,
    SequenceExecution,
    SequenceStep,
)
from app.database.models.project import Project
from app.database.models.refresh_token import RefreshTokenSession
from app.database.models.role import Role
from app.database.models.task import Task
from app.database.models.user import User
from app.database.models.user_role import UserRole

__all__ = [
    "Base",
    "AgentApproval",
    "AgentApprovalStatus",
    "AgentAttachment",
    "AgentAttachmentStatus",
    "AgentContextSnapshot",
    "AgentConversation",
    "AgentDefinition",
    "AgentMemory",
    "AgentMemoryScope",
    "AgentMemoryType",
    "AgentMessage",
    "AgentRiskLevel",
    "AgentRun",
    "AgentRunStatus",
    "AgentStatus",
    "AgentToolDefinition",
    "AgentToolExecution",
    "ConversationPriority",
    "ConversationStatus",
    "MessageContentType",
    "MessageRole",
    "ToolExecutionMode",
    "ToolExecutionStatus",
    "AuditAction",
    "AuditEntity",
    "AuditLog",
    "BackgroundJobAttempt",
    "BackgroundJobDefinition",
    "BackgroundJobEvent",
    "BackgroundJobExecution",
    "BackgroundJobSchedule",
    "ApprovalStatus",
    "AutomationAction",
    "AutomationRule",
    "AutomationTrigger",
    "Campaign",
    "DeliveryEvent",
    "DeliveryEventType",
    "DraftStatus",
    "DynamicAudience",
    "EmailAttachment",
    "EmailDraft",
    "EmailTemplate",
    "EmailTemplateVersion",
    "MailboxConnection",
    "MailboxProvider",
    "OutreachApproval",
    "OutreachStatus",
    "QueueStatus",
    "SendQueueItem",
    "Sequence",
    "SequenceEnrollment",
    "SequenceExecution",
    "SequenceStep",
    "CRMActivity",
    "CRMActivityType",
    "CRMNote",
    "Company",
    "CompanyStatus",
    "Contact",
    "ContactStatus",
    "Deal",
    "DealStatus",
    "Lead",
    "LeadSource",
    "LeadStatus",
    "Notification",
    "NotificationType",
    "Project",
    "ProjectStatus",
    "RefreshTokenSession",
    "Pipeline",
    "PipelineStage",
    "Role",
    "Task",
    "TaskPriority",
    "TaskStatus",
    "TimestampMixin",
    "UUIDPrimaryKeyMixin",
    "User",
    "UserRole",
]
